include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print                     # 用 debugPrint
    - prefer_const_constructors       # 性能关键
    - require_trailing_commas         # 格式化友好
    - use_super_parameters

analyzer:
  language:
    strict-casts: true              # 禁止隐式类型转换
    strict-inference: true          # 类型推断缺失时报错
    strict-raw-types: true          # 禁止省略泛型参数
  errors:
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
    missing_enum_constant_in_switch: error
  exclude:
    - "**/*.g.dart"                      # 排除代码生成文件
    - "**/*.freezed.dart"